### PR TITLE
Fix `CausalConeSimulator` by replacing `QuantumGateBase::set_target_qubit_index`

### LINKED ISSUE #659: Problems with the gradient computation
Dear devs,

First of all, thank you for your amazing work.

Recently I found an "issue" that is provided in the attached code snippets. 

Basically, the time taken for gradient computation can drastically change (a factor of 10^6) and even given different results when using the same circuit and the same function depending on how the gate is added. You can in principle add a parametric X gate (option 1), what is slow. Or you can add a multiqubit parametric Pauli rotation specified for a single qubit X. If the latter is done by defining a list `target` with all the qubits in the circuit and placing identities (this is `0`) in the list `pauli_id` (option 2), then the result is correct as expected and it is way faster than the single parametric gate. However, if the lists `target` and `pauli_id` are defined only with qubits on which the rotation is not acting with an identity (option 3), then  the time taken is almost as slow as for a single parametric gate but also if the rotation is made on a qubit that is not the first one, then the result can be wrong (check snippet 2). The rule seems to be that if one includes in both lists all the qubits `j` whose index is smaller than the one on which the rotation is applied, then the multi qubit parametric rotation is faster and gives the right result. I tried to see where the issue is coming from and I believe it is inside the CausalConeSimulator computation.

I believe this might also be related to previously reported issues like [this one](https://discuss.pennylane.ai/t/qualcs-device-and-qml-grad-timings/1717).

Snippet 1
```python
from qulacs import ParametricQuantumCircuit, GradCalculator, Observable
from time import time

n = 2
observable = Observable(n)
observable.add_operator(1.0, "X 0")
observable.add_operator(1.0, "X 1")
observable.add_operator(1.0, "Z 0 Z 1")

theta = 2.2

# option 1
t1 = time()
circuit = ParametricQuantumCircuit(n)
circuit.add_parametric_RX_gate(0, theta)
gcalc = GradCalculator()
result1 = gcalc.calculate_grad(circuit, observable)
t2 = time()
print("Option 1:",result1)
print("Time 1:",t2-t1)

# option 2
t3 = time()
target = [0]
pauli_ids = [1]
circuit = ParametricQuantumCircuit(n)
circuit.add_parametric_multi_Pauli_rotation_gate(target, pauli_ids, theta)
gcalc = GradCalculator()
result2 = gcalc.calculate_grad(circuit, observable)
t4 = time()
print("Option 2:",result2)
print("Time 2:",t4-t3)

# option 3
t5 = time()
target = [0,1]
pauli_ids = [1,0]
circuit = ParametricQuantumCircuit(n)
circuit.add_parametric_multi_Pauli_rotation_gate(target, pauli_ids, theta)
gcalc = GradCalculator()
result3 = gcalc.calculate_grad(circuit, observable)
t6 = time()
print("Option 3:",result3)
print("Time 3:",t6-t5)
```
```
Option 1: [(-0.8084964038195901+0j)]
Time 1: 14.150959968566895
Option 2: [(-0.8084964038195901+0j)]
Time 2: 11.57673692703247
Option 3: [(-0.8084964038195901+0j)]
Time 3: 0.00026416778564453125
```

Snippet 2
```python
n = 2
observable = Observable(n)
observable.add_operator(0.3, "X 0")
observable.add_operator(0.8, "X 1")
observable.add_operator(1.1, "Z 0 Z 1")

theta = 2.2

# option 1
t1 = time()
circuit = ParametricQuantumCircuit(n)
circuit.add_parametric_RX_gate(1, theta)
gcalc = GradCalculator()
result1 = gcalc.calculate_grad(circuit, observable)
t2 = time()
print("Option 1:",result1)
print("Time 1:",t2-t1)

# option 2
t3 = time()
target = [1]
pauli_ids = [1]
circuit = ParametricQuantumCircuit(n)
circuit.add_parametric_multi_Pauli_rotation_gate(target, pauli_ids, theta)
gcalc = GradCalculator()
result2 = gcalc.calculate_grad(circuit, observable)
t4 = time()
print("Option 2:",result2)
print("Time 2:",t4-t3)

# option 3
t5 = time()
target = [0,1]
pauli_ids = [0,1]
circuit = ParametricQuantumCircuit(n)
circuit.add_parametric_multi_Pauli_rotation_gate(target, pauli_ids, theta)
gcalc = GradCalculator()
result3 = gcalc.calculate_grad(circuit, observable)
t6 = time()
print("Option 3:",result3)
print("Time 3:",t6-t5)
```
```
Option 1: [(-0.8893460442015492+0j)]
Time 1: 14.029311895370483
Option 2: [(0.4079469997759596+0j)]
Time 2: 13.821652889251709
Option 3: [(-0.8893460442015492+0j)]
Time 3: 0.0003330707550048828

```

### PR DESCRIPTION
**Pull request by KowerKoint**
close #659 

`QuantumGateBase::set_target_qubit_index` was wrong because it didn't replace target indices of `PauliOperator` on `ClsPauliGate` etc.
I think this function is evil. Replacing target qubit index later makes trouble easily.
So this time I created a new function to make copied gate with targets replaced.

In addition, I found some wrong parts in `CausalConeSimulator` and fix them.

### CODE REVIEW

File: src/cppsim/gate_named_pauli.hpp [hunk 1]
```diff
@@ -107,6 +107,30 @@ class ClsPauliGate : public QuantumGateBase {
...
+                "replaced\n qubit count of control_index_list does not match.");
+        }
+        PauliOperator* pauli = new PauliOperator(
+            target_index_list, _pauli->get_pauli_id_list(), _pauli->get_coef());
+        auto ret = new ClsPauliGate(pauli);
+        delete pauli;
+        return ret;
+    }
+
+    virtual QuantumGateBase* get_inverse() const override { return copy(); }
```
Comment (KowerKoint) [inline src/cppsim/gate_named_pauli.hpp:133]: I found `ClsPauliGate::get_inversed` has not been defined, then I appended.

File: src/vqcsim/causalcone_simulator.hpp [hunk 2]
```diff
@@ -74,7 +73,7 @@ class DllExport CausalConeSimulator {
             const UINT gate_count = init_circuit->gate_list.size();
             const UINT qubit_count = init_circuit->qubit_count;
             const UINT observable_count = observable_index_list.size();
-            UnionFind uf(qubit_count + observable_count);
+            UnionFind uf(qubit_count);
```
Comment (KowerKoint) [inline src/vqcsim/causalcone_simulator.hpp:76]: UF nodes of observable is not used.

File: src/vqcsim/causalcone_simulator.hpp [hunk 3]
```diff
@@ -92,14 +91,6 @@ class DllExport CausalConeSimulator {
...
                     }
                 }
-                if (!use_gate[i]) {
-                    for (auto control_index : control_index_list) {
-                        if (use_qubit[control_index]) {
-                            use_gate[i] = true;
-                            break;
-                        }
-                    }
-                }
```
Comment (KowerKoint) [inline src/vqcsim/causalcone_simulator.hpp:102]: control qubits are not changed and make no effects, so it can be removed.

File: .github/workflows/ci_macos.yml [hunk 4]
```diff
@@ -44,17 +44,17 @@ jobs:
...
       - name: Install Boost for macOS
         run: |
           brew update
           brew install boost
           brew link boost
 
+      - name: Setup Python
+        uses: actions/setup-python@v5
+        with:
+          python-version: ${{ matrix.python-version }}
```
Comment (KowerKoint) [inline .github/workflows/ci_macos.yml:56]: deal with https://github.com/qulacs/qulacs/actions/runs/11227525405

File: src/cppsim/circuit_optimizer.hpp [hunk 5]
```diff
@@ -34,16 +34,31 @@ class DllExport QuantumCircuitOptimizer {
...
+
+        QuantumGateBase* get_replaced_gate(QuantumGateBase* gate) {
+            if (!replace.count(gate)) return gate;
+            return replace[gate] = get_replaced_gate(replace[gate]);
+        }
+
+        void set_replaced_gate(QuantumGateBase* from, QuantumGateBase* to) {
+            replace[from] = to;
+        }
+    };
```
Comment (KowerKoint) [inline src/cppsim/circuit_optimizer.hpp:48]: Optimization by swap insertion modify target qubit indices but manage gates by pointer.
New function `create_gate_whose_qubit_indices_are_replaced` changes gate pointer, so I created this `replacer`, manage replacement by referencing it, and actually replace gates later.

File: src/cppsim/circuit_optimizer.hpp [hunk 6]
```diff
@@ -34,16 +34,31 @@ class DllExport QuantumCircuitOptimizer {
...
+    struct GateReplacer {
+        std::map<QuantumGateBase*, QuantumGateBase*> replace;
+
+        QuantumGateBase* get_replaced_gate(QuantumGateBase* gate) {
+            if (!replace.count(gate)) return gate;
+            return replace[gate] = get_replaced_gate(replace[gate]);
+        }
+
+        void set_replaced_gate(QuantumGateBase* from, QuantumGateBase* to) {
+            replace[from] = to;
```
Comment (kotamanegi) [inline src/cppsim/circuit_optimizer.hpp:46]: Overwriting existing references to other references is forbidden in the union-find algorithm.
```cpp
// Sample
QuantumGateBase* A,B,C,D;
set_replaced_gate(A,B);
set_replaced_gate(B,C);
get_replaced_gate(A); // replace[A] is set to C
set_replaced_gate(B,D);
get_replaced_gate(A): // return value expects D, but was C.
```
Please add error handling codes or use normal traversal method without route compression.

```suggestion
            if(replace.count(gate))
              // throw errors here.
            replace[from] = to;
```

**Review by kotamanegi — CHANGES_REQUESTED** [review]
Looks pretty good to me!
I found some niche problems in the code. I would be grateful if you resolve points of concern.

File: .github/workflows/ci_macos.yml [hunk 7]
```diff
@@ -44,17 +44,19 @@ jobs:
...
-          python-version: ${{ matrix.python-version }}
-
+      # ignore python link issue https://github.com/qulacs/qulacs/actions/runs/11227598146/job/31210081471
+      # ref: https://github.com/actions/runner-images/issues/8500
       - name: Install Boost for macOS
         run: |
           brew update
-          brew install boost
+          brew install boost || true
           brew link boost
```
[the remark this answers is not in the document]
Comment (KowerKoint) [reply .github/workflows/ci_macos.yml]: It seems better. Thank you.

File: .github/workflows/ci_macos.yml
[the remark this answers is not in the document]
Comment (KowerKoint) [reply .github/workflows/ci_macos.yml:1]: I see.
I reverted on this branch and put the change on #662 .

File: src/cppsim/circuit_optimizer.hpp (hunk 6 above)
Comment (KowerKoint) [reply src/cppsim/circuit_optimizer.hpp:52]: handled on https://github.com/qulacs/qulacs/pull/661/commits/ca320c54455f3b4bcaad62ece930dffe26c2dbda

**Review by kotamanegi — APPROVED** [review]
Looks Good:+1:
